// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project_Resturant_MVC.Context;

#nullable disable

namespace Project_Resturant_MVC.Migrations
{
    [DbContext(typeof(ResturantDbContext))]
    [Migration("20251024144134_AddImageUrlToMenuItemsInSeed")]
    partial class AddImageUrlToMenuItemsInSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Project_Resturant_MVC.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Project_Resturant_MVC.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 24, 14, 41, 33, 312, DateTimeKind.Utc).AddTicks(5167),
                            Description = "Start your meal with our delicious appetizers",
                            IsDeleted = false,
                            Name = "Appetizers"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 24, 14, 41, 33, 312, DateTimeKind.Utc).AddTicks(5169),
                            Description = "Hearty and satisfying main dishes",
                            IsDeleted = false,
                            Name = "Main Courses"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 10, 24, 14, 41, 33, 312, DateTimeKind.Utc).AddTicks(5170),
                            Description = "Sweet treats to end your meal",
                            IsDeleted = false,
                            Name = "Desserts"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 10, 24, 14, 41, 33, 312, DateTimeKind.Utc).AddTicks(5172),
                            Description = "Refreshing drinks",
                            IsDeleted = false,
                            Name = "Beverages"
                        });
                });

            modelBuilder.Entity("Project_Resturant_MVC.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PreparationTimeMinutes")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 10, 24, 14, 41, 33, 312, DateTimeKind.Utc).AddTicks(5325),
                            Description = "Crispy wings with buffalo sauce",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Chicken Wings",
                            PreparationTimeMinutes = 15,
                            Price = 45.00m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 10, 24, 14, 41, 33, 312, DateTimeKind.Utc).AddTicks(5329),
                            Description = "Fried cheese sticks with marinara",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Mozzarella Sticks",
                            PreparationTimeMinutes = 10,
                            Price = 35.00m,
                            Quantity = 8
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 10, 24, 14, 41, 33, 312, DateTimeKind.Utc).AddTicks(5332),
                            Description = "Fresh romaine with parmesan and croutons",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Caesar Salad",
                            PreparationTimeMinutes = 8,
                            Price = 40.00m,
                            Quantity = 7
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 10, 24, 14, 41, 33, 312, DateTimeKind.Utc).AddTicks(5335),
                            Description = "Classic pizza with tomato, mozzarella, and basil",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Margherita Pizza",
                            PreparationTimeMinutes = 20,
                            Price = 85.00m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 10, 24, 14, 41, 33, 312, DateTimeKind.Utc).AddTicks(5337),
                            Description = "Juicy beef patty with cheese and fries",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Beef Burger",
                            PreparationTimeMinutes = 18,
                            Price = 95.00m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 10, 24, 14, 41, 33, 312, DateTimeKind.Utc).AddTicks(5340),
                            Description = "Creamy pasta with bacon and parmesan",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Pasta Carbonara",
                            PreparationTimeMinutes = 15,
                            Price = 80.00m,
                            Quantity = 6
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 10, 24, 14, 41, 33, 312, DateTimeKind.Utc).AddTicks(5342),
                            Description = "Marinated chicken breast with vegetables",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Grilled Chicken",
                            PreparationTimeMinutes = 25,
                            Price = 110.00m,
                            Quantity = 12
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 10, 24, 14, 41, 33, 312, DateTimeKind.Utc).AddTicks(5345),
                            Description = "Rich chocolate layer cake",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Chocolate Cake",
                            PreparationTimeMinutes = 5,
                            Price = 50.00m,
                            Quantity = 20
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 10, 24, 14, 41, 33, 312, DateTimeKind.Utc).AddTicks(5347),
                            Description = "Creamy New York style cheesecake",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Cheesecake",
                            PreparationTimeMinutes = 5,
                            Price = 55.00m,
                            Quantity = 15
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 10, 24, 14, 41, 33, 312, DateTimeKind.Utc).AddTicks(5350),
                            Description = "Three scoops with toppings",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Ice Cream Sundae",
                            PreparationTimeMinutes = 3,
                            Price = 40.00m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 10, 24, 14, 41, 33, 312, DateTimeKind.Utc).AddTicks(5352),
                            Description = "Freshly squeezed orange juice",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Fresh Orange Juice",
                            PreparationTimeMinutes = 3,
                            Price = 25.00m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 10, 24, 14, 41, 33, 312, DateTimeKind.Utc).AddTicks(5355),
                            Description = "Italian style coffee with foam",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Cappuccino",
                            PreparationTimeMinutes = 5,
                            Price = 30.00m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 10, 24, 14, 41, 33, 312, DateTimeKind.Utc).AddTicks(5357),
                            Description = "Coca Cola, Sprite, or Fanta",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Soft Drink",
                            PreparationTimeMinutes = 1,
                            Price = 15.00m,
                            Quantity = 10
                        });
                });

            modelBuilder.Entity("Project_Resturant_MVC.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("EstimatedDeliveryMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ReadyAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 24, 14, 41, 33, 312, DateTimeKind.Utc).AddTicks(5407),
                            CustomerName = "Ahmed Ali",
                            CustomerPhone = "01012345678",
                            DeliveryAddress = "Cairo, Nasr City",
                            Discount = 0.00m,
                            IsDeleted = false,
                            Status = 3,
                            Subtotal = 180.00m,
                            Tax = 0.00m,
                            Total = 180.00m,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 24, 14, 41, 33, 312, DateTimeKind.Utc).AddTicks(5410),
                            CustomerName = "Sara Mohamed",
                            CustomerPhone = "01098765432",
                            DeliveryAddress = "Giza, Dokki",
                            Discount = 0.00m,
                            IsDeleted = false,
                            Status = 0,
                            Subtotal = 95.00m,
                            Tax = 0.00m,
                            Total = 95.00m,
                            Type = 1
                        });
                });

            modelBuilder.Entity("Project_Resturant_MVC.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 24, 14, 41, 33, 312, DateTimeKind.Utc).AddTicks(5520),
                            IsDeleted = false,
                            MenuItemId = 5,
                            OrderId = 1,
                            Quantity = 1,
                            Subtotal = 95.00m,
                            UnitPrice = 95.00m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 24, 14, 41, 33, 312, DateTimeKind.Utc).AddTicks(5523),
                            IsDeleted = false,
                            MenuItemId = 8,
                            OrderId = 1,
                            Quantity = 1,
                            Subtotal = 50.00m,
                            UnitPrice = 50.00m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 10, 24, 14, 41, 33, 312, DateTimeKind.Utc).AddTicks(5526),
                            IsDeleted = false,
                            MenuItemId = 11,
                            OrderId = 1,
                            Quantity = 1,
                            Subtotal = 25.00m,
                            UnitPrice = 25.00m
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 10, 24, 14, 41, 33, 312, DateTimeKind.Utc).AddTicks(5528),
                            IsDeleted = false,
                            MenuItemId = 4,
                            OrderId = 2,
                            Quantity = 1,
                            Subtotal = 85.00m,
                            UnitPrice = 85.00m
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 10, 24, 14, 41, 33, 312, DateTimeKind.Utc).AddTicks(5530),
                            IsDeleted = false,
                            MenuItemId = 13,
                            OrderId = 2,
                            Quantity = 1,
                            Subtotal = 10.00m,
                            UnitPrice = 10.00m
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Project_Resturant_MVC.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Project_Resturant_MVC.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project_Resturant_MVC.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Project_Resturant_MVC.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Project_Resturant_MVC.Models.MenuItem", b =>
                {
                    b.HasOne("Project_Resturant_MVC.Models.Category", "Category")
                        .WithMany("MenuItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Project_Resturant_MVC.Models.OrderItem", b =>
                {
                    b.HasOne("Project_Resturant_MVC.Models.MenuItem", "MenuItem")
                        .WithMany("OrderItems")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Project_Resturant_MVC.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Project_Resturant_MVC.Models.Category", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("Project_Resturant_MVC.Models.MenuItem", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Project_Resturant_MVC.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
